.PHONY: alla
alla:
	ln -s ../../.bender/git/checkouts/$(shell basename ../../.bender/git/checkouts/tbtools*)/dpi_models/ .
	ln -s ../../.bender/git/checkouts/$(shell basename ../../.bender/git/checkouts/tbtools*)/tb_driver/ .